
module.exports = {
  pylos: {
    INSERT: 'INSERT',
    LIFT: 'LIFT',
    REMOVE: 'REMOVE',
    COMMIT: 'COMMIT',
    OVERRIDE_STATE: 'OVERRIDE_STATE',
    OVERRIDE_HISTORY: 'OVERRIDE_HISTORY'
  },
  ui: {
    SELECT: 'SELECT',
    UNSELECT: 'UNSELECT',
    ALLOW_REMOVALS: 'ALLOW_REMOVALS',
    DISALLOW_REMOVALS: 'DISALLOW_REMOVALS',
    CHANGE_SIZE: 'CHANGE_SIZE'
  }
}
